### ISSUE TITLE
Color themes

### ISSUE THREAD

**Issue by digitaldias** [Danielhiversen/home_assistant_tibber_custom#38]
Love this integration, but it is in desperate need of some color theming. Right now, the white is making me blind, and sadistically destroys my current theme (I'm using mushroom theme btw). Something to the likes of: 

```
tibber_custom:
  background_color: darkblue
  line_color: blue
  fill_color: evenBluer
  font_color: yello
  ```
Also, sidenote: The image I get looks nothing like what you have in the readme. Those look way better :)
![image](https://user-images.githubusercontent.com/929421/182332720-bfe68c17-9c5d-41c6-8253-60ae1f124342.png)
This is what I'm looking at
