### ISSUE TITLE
Future Price

### ISSUE THREAD

**Issue by nesnajkneh** [Danielhiversen/home_assistant_tibber_custom#62]
Hi, 

I would like to program an EMS in home assistant. But essential for that are the upcoming prices from tibber. Is it anyhow possible to get this in HA?

**Comment by psychogun** [comment]
If you live in Europe, just utilize the Nord Pool integration instead?

**Comment by psychogun** [comment]
Settings > Devices & services > + Add integration : Nord Pool.

Configure Nord Pool for your area. Example further down is shown for "Norway 2 (NO2)".

Developer Tools > Actions > Go to UI mode >
Search / Look for anything Nordpool
Perform Action
Go to "YAML mode" 
Note down your `config_entry` value.

Go to Settings > Devices & services > Helpers >  + Create helper
Select `Number`. 

Name: NO2 price 00
Minimum value: -10
Maximum value: 20
Click Create.

Edit the helper, go to Advanced settings and change Entity ID*: `input_number.nordpool_no2_h_00`

Do that 23 more times. ..
`...`
`input_number.nordpool_no2_h_21`
`input_number.nordpool_no2_h_22`

Name: NO2 price 23
Minimum value: -10
Maximum value: 20
Click Create .. 

Remember to change Entity ID* for all newly created helpers and click Update:
`input_number.nordpool_no2_h_23`

This example is an automation that stores the next day's values (local time skewed +2 hours) in the helper numbers. It is guaranteed that Nord Pool have these prices out between 13:00 and 15:00 (Norwegian time), therefore run time is set to 15:10. 


```yaml
alias: NordPool - Store Tomorrow 24h Prices @15:10 (NO2)
description: Fetch NO2 prices for tomorrow at 15:10 and store into 24 helpers
triggers:
  - trigger: time
    at: "15:10:00"
conditions: []
actions:
  - variables:
      zone: NO2
      target_date: "{{ (now() + timedelta(days=1)).strftime('%Y-%m-%d') }}"
  - action: nordpool.get_prices_for_date
    response_variable: nordpool_data
    data:
      config_entry: <retracted>>
      date: "{{ target_date }}"
  - condition: template
    value_template: >-
      {{ nordpool_data and zone in nordpool_data and (nordpool_data[zone] |
      count) >= 1 }}
  - variables:
      hours_to_store: "{{ [24, (nordpool_data[zone] | count)] | min }}"
  - repeat:
      count: "{{ hours_to_store | int }}"
      sequence:
        - variables:
            idx: "{{ repeat.index - 1 }}"
            ent_id: >-
              {{ 'input_number.nordpool_no2_h_' ~ ('%02d' | format(repeat.index
              - 1)) }}
            price_kwh: >-
              {{ (nordpool_data[zone][repeat.index - 1].price | float(0)) / 1000
              }}
        - action: input_number.set_value
          data:
            entity_id: "{{ ent_id }}"
            value: "{{ price_kwh }}"
  - action: notify.mobile_app_user
    data:
      title: NordPool NO2 forecast stored
      message: Saved {{ hours_to_store }} hourly prices for {{ target_date }}.
mode: single

```

Then you can create an automation that finds, for example, the cheapest 3 hour timeblock? I use this automation to get notified to when it is cheapest to run appliances during the night: 

```yaml
alias: NordPool - Cheapest 3h Block 00-08 @23:00 NO2
description: >-
  Finds tomorrow's cheapest 3-hour block between 00:00 and 08:00 in NO2 and
  notifies at 23:00 local time
triggers:
  - trigger: time
    at: "23:00:00"
conditions: []
actions:
  - variables:
      target_date: "{{ (now() + timedelta(days=1)).strftime('%Y-%m-%d') }}"
      zone: NO2
  - action: nordpool.get_prices_for_date
    response_variable: nordpool_data
    data:
      config_entry: <retracted>
      date: "{{ target_date }}"
  - action: notify.mobile_app_user
    data:
      title: Cheapest 3h block 00-08 for {{ target_date }} ({{ zone }})
      message: >
        {% set prices = nordpool_data[zone] if nordpool_data and (zone in
        nordpool_data) else [] %} {% set n = prices|count %} {% if n < 3 %} No
        price data available for {{ target_date }} (zone {{ zone }}). {% else %}
        {% set max_start = 5 if n >= 8 else (n - 3) %} {% set ns =
        namespace(min_sum=None, idxs=[]) %} {% for i in range(0, max_start + 1)
        %}
          {% set s = prices[i].price + prices[i+1].price + prices[i+2].price %}
          {% if ns.min_sum is none or s < ns.min_sum %}
            {% set ns.min_sum = s %}
            {% set ns.idxs = [i] %}
          {% elif s == ns.min_sum %}
            {% set ns.idxs = ns.idxs + [i] %}
          {% endif %}
        {% endfor %} {% set avg_kwh = (ns.min_sum / 3 / 1000) %} Cheapest 3-hour
        block(s) between 00:00 and 08:00, average {{ avg_kwh | round(2) }}
        NOK/kWh: {% for i in ns.idxs %} {{ "%02d"|format(i) }}:00-{{
        "%02d"|format(i + 3) }}:00 H1 ({{ "%02d"|format(i) }}:00): {{
        (prices[i].price / 1000) | round(2) }} NOK/kWh H2 ({{ "%02d"|format(i+1)
        }}:00): {{ (prices[i+1].price / 1000) | round(2) }} NOK/kWh H3 ({{
        "%02d"|format(i+2) }}:00): {{ (prices[i+2].price / 1000) | round(2) }}
        NOK/kWh {% endfor %} {% endif %}
mode: single
```

I am (yet?) unable to render this in a graph in Home Assistant. However, I can show the future price as entities by doing the following: 
Create a new helper, Template - Template a sensor:

Name: NO2 tomorrow 00
State* : `{{ states('input_number.nordpool_no2_h_00') | float(0) }}`
Unit of measurement: NOK/kWh

Do that 23 more times. .. "NO2 tomorrow 01" > `...ool_no2_h_01'` etc. and then you can show 
`sensor.no2_tomorrow_01` in your dashboard? Maybe this can help you create an automation that does something based on the cheapest hours of the day, @nesnajkneh 

PS: You can change  `timedelta(days=1))` to  `timedelta(days=0))` to get todays date electricity prices. Dependent on your needs you maybe have to create additional 24 helper numbers or execute the automation more often.

But having this through the Tibber integration would be smoother, I guess.
